language: cpp

sudo: false

notifications:
  email:
    on_success: never
    on_failure: always

matrix:
  include:
  # Test
  - os: linux
    dist: xenial
    language: python
    python:
      - "3.7"
  # Linux, GCC8
  - os: linux
    dist: xenial
    compiler: gcc
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-8', 'python3.7.1']
    env: COMPILER=g++-8
    before_script:
      - pip install --user conan
  # Linux, Clang8
  - os: linux
    dist: xenial
    compiler: clang
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-8.0']
        packages: ['g++-8', 'clang-8.0', 'python3.7.1']
    env: COMPILER=clang++-8.0
    before_script:
      - pip install --user conan
  # OSX, Clang
  - os: osx
    osx_image: xcode10
    compiler: clang
    env: COMPILER=clang++
    before_script:
      - pip install --user conan
  # Linux, GCC8, coverage
  - os: linux
    dist: xenial
    compiler: gcc
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-8', 'python3.7.1']
    env:
      - COMPILER=g++-8
      # CMake automatically imports this as C++ flags
      - CXXFLAGS="-O0 -g --coverage -fno-inline -fno-inline-small-functions -fno-default-inline"
    before_script:
      - pip install --user conan
      - pip install --user cpp-coveralls
    after_success:
      - coveralls --gcov gcov-8 --gcov-options '\-lp' --root ${TRAVIS_BUILD_DIR} --build-root ${TRAVIS_BUILD_DIR}/build --extension cpp --extension hpp --exclude deps --include src

install:
  - cmake --version
  - export CXX=${COMPILER}
  - echo ${CXX}
  - ${CXX} --version
  - ${CXX} -v

script:
  - mkdir -p build && cd build
  # Generate and build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make -j 4
  # Run tests
  - CTEST_OUTPUT_ON_FAILURE=1
  - ctest -j 4
