language: cpp

sudo: true

notifications:
  email:
    on_success: never
    on_failure: always

matrix:
  include:
  # Linux, GCC8
  - os: linux
    dist: xenial
    compiler: gcc
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'deadsnakes']
        packages: ['g++-8', 'python3.6']
    env: COMPILER=g++-8
    before_script:
      - pip install --user conan
  # Linux, Clang8
  - os: linux
    dist: xenial
    compiler: clang
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-8', 'deadsnakes']
        packages: ['g++-8', 'clang-8', 'libc++-dev', 'libc++abi-dev', 'python3.6']
    env:
      - COMPILER=clang++-8
      - CXXFLAGS="${CXXFLAGS} -stdlib=libc++"
    before_script:
      - pip install --user conan
  # TODO: Fix, need Python3.6
  # OSX, Clang
  #- os: osx
  #  osx_image: xcode10
  #  compiler: clang
  #  env: COMPILER=clang++
  #  before_script:
  #    - pip install --user conan
  # Linux, GCC8, coverage
  - os: linux
    dist: xenial
    compiler: gcc
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'deadsnakes']
        packages: ['g++-8', 'python3.6']
    env:
      - COMPILER=g++-8
      # CMake automatically imports this as C++ flags
      - CXXFLAGS="-O0 --coverage -fno-inline -fno-inline-small-functions -fno-default-inline"
    before_script:
      - pip install --user conan
      - pip install --user cpp-coveralls
    after_success:
      - coveralls --gcov gcov-8 --gcov-options '\-lp' --root ${TRAVIS_BUILD_DIR} --build-root ${TRAVIS_BUILD_DIR}/build --extension cpp --extension hpp --exclude deps --include single_include

install:
  - python --version
  - cmake --version
  - export CXX=${COMPILER}
  - echo ${CXX}
  - ${CXX} --version
  - ${CXX} -v

script:
  - mkdir -p build && cd build
  # Generate and build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make -j 4
  # Run tests
  - CTEST_OUTPUT_ON_FAILURE=1
  - ctest -j 4
